import type { Metadata } from "next"
import { Nunito } from "next/font/google"
import "./globals.css"
import Navbar from "../components/navbar/navbar"
import Footer from "../components/footer/footer"
import 'react-toastify/dist/ReactToastify.css'
import { ToastContainer } from 'react-toastify'



const nunito = Nunito({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "smart.",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
          <Navbar />
            {children}
          <Footer />
          <ToastContainer />    

      </body>
    </html>
  )
}
